### PR TITLE
Fix the issue of the missing (i) icon next to qtype in search widgets (issue #827)

### LINKED ISSUE #827: The tooltip for Any/All/Only has gone away
There used to be an (i) next to the any/all/only dropdown that showed a pop-out with some basic information. See #196 for an example (the text one, not the graphics one). Sometime with all of our modifications this went away, and it needs to be brought back.

### PR DESCRIPTION
**Pull request by juzen2003**
- Fixes #827 
- Local branch: tooltip_issue_for_any_all_only_827
- Use the same popover method for the hover over event on (i) icon next to qtype.

### CODE REVIEW

File: opus/application/static_media/js/widgets.js [hunk 1]
```diff
@@ -409,6 +409,27 @@ var o_widgets = {
                 o_hash.updateHash();
             }
 
+            // If we have a widget with qtype options any/all/only, we will append the (i) icon.
+            if ($(`#widget__${slug} select[name="${qtype}"]`).length !== 0) {
```
Comment (dstopp) [inline opus/application/static_media/js/widgets.js:406]: What do you think about combining the previous 'if' block and just do all the "${qtype}" business together?

File: opus/application/apps/ui/templates/ui/base.html [hunk 2]
```diff
@@ -453,7 +453,7 @@ <h3 class='op-header-text'></h3>
     <div class="op-overlay"></div>
 
     {% include "ui/footer.html" %}
-    <div id="range_query_widget_helper_html">
+    <div id="op-range-qtype-helper-html">
```
Comment (dstopp) [inline opus/application/apps/ui/templates/ui/base.html]: What do you think of renaming the id to "op-qtype-tooltip" instead?  I'm not clear that we need 'helper' or 'html' in that name and my thought is that this is just the tooltip for the qtype.

**Review by dstopp — CHANGES_REQUESTED** [review]

**Comment by juzen2003** [comment]
- Update based on Debby's comments.

**Review by dstopp — APPROVED** [review]
