### PR TITLE
1382 browse tab wrong focus on click

### LINKED ISSUE #1382: Arrow and page up/down keys have wrong focus
- Go to the Browse Results tab
- Drag the slider to some random location
- Use the up and down arrows to navigate; the screen will scroll in the wrong direction
- Use the page up/down keys to navigate: the screen with jump by thousands of thumbnails instead of one page

Both of these are caused by the focus being wrong. When you click on the slider, the focus stays there, and the various shortcut keys operate on the slider, not the main thumbnail pane. I don't think this used to happen. We need those keystrokes to be forwarded to the thumbnail pane no matter where the focus is in the Browse Tab. For example, right now if you click on the word "Sort By" you will no longer be able to use those keys.

### PR DESCRIPTION
**Pull request by juzen2003**
- Fixes #1382
- Is a new database import required? N
- Were test and deploy scripts reviewed for necessary changes? NA
- Were any JavaScript or CSS files modified? Y
  - If YES:
    - JSHINT run on all affected files: Y
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: Y
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): NA
- Was the documentation reviewed for necessary changes or additions? NA
  - About
  - Getting Started
  - FAQ
  - API Guide
  - Tooltips
  - Import/database schema

Description of changes:

- For perfect scrollbar to handle any keydown event, we have to make sure the ps container is hovered and perfect scrollbar is focused. This is the required step from the source code (`perfect-scrollbar.js` line  629-631). So whenever we click or hit up/down arrows, and page up/down keys in browse tab, we make sure the ps container is hovered and ps is focused so the the keydown event will be properly handled by ps, and the observations view can be properly scrolled.
- For record, if we undo all the changes in `browse.js`, and just comment out line 629-631 in `perfect-scrollbar.js`, we can achieve the same behavior.
- Update on 7/26/24: 
  - Disable the up/down and left/right arrow keys to switch between different tabs when we click on the top nav bar.
  - Now in the browse view, the up/down and page up/down keys will only control the perfect scrollbar of the observations view, and it will work no matter where the mouse cursor is on the screen.
  - Test on Windows 11 with Chrome (119-126), Firefox (120-128), and Edge (119-126). Mac Sonoma latest Chrome, Firefox, and Safari.

Known problems:
 
 <div id='description'>
<h3>Summary by Bito</h3>
The changes primarily focus on improving user interface interactions and scroll behavior. In the CSS file, styles were added to remove highlight borders on focus. The JavaScript files saw multiple updates to handle scroll positions, event bindings, and synchronization of scrollbar positions. Additionally, navigation click handling and focus management were enhanced to improve user experience.
<br>
<br>
<b>Code change type</b>: Refactoring, Performance Improvement, Accessibility, Functionality
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>

### CODE REVIEW

**Comment by rfrenchseti** [comment]
There is still a problem with the slider. With Chrome on Linux and Windows, and Firefox on Windows, if I grab the slider and move it a large distance, then let go and don't move the mouse, I can't use the keys. In fact I can move the mouse anywhere in the top area and the keys don't work. But if I move the mouse into the thumbnail area it starts to work.

**Comment by juzen2003** [comment]
The issue is fixed, test on Windows 11 with Chrome (119-126), Firefox (120-128), and Edge (119-126) in Browserstack, and Mac Sonoma with the latest Chrome, Firefox, and Safari using my local machine. Can't test on Linux since there is no Linux OS in Browserstack. Descriptions of changes in the top comment is updated.

**Review by rfrenchseti — CHANGES_REQUESTED** [review]
Two issues:
1) When you open any Help dialog (like About or Bundles/Volumes), using the up/down or page up/page down keys still scroll the thumbnails in the background, not the text in the dialog.
2) When you switch from Gallery to Table view, the top line of the Table view is not the same image number as the top-left thumbnail in the Gallery (in other words, the slider moves when you switch views).

File: opus/application/static_media/js/browse.js [hunk 1]
```diff
@@ -136,8 +136,11 @@ var o_browse = {
 
             o_hash.updateURLFromCurrentHash();
             o_browse.updateBrowseNav();
-            // reset scroll position
-            window.scrollTo(0, 0); // restore previous scroll position
+            // Make sure trFloor is properly set for calculations
+            let viewNamespace = opus.getViewNamespace()
+            if (viewNamespace.galleryBoundingRect.trFloor===Infinity) {
```
Comment (rfrenchseti) [inline opus/application/static_media/js/browse.js]: We normally have spaces around operators like `===`

**Comment by rfrenchseti** [comment]
<div>
<h2>Code Review Agent Run #c06976</h2>
<div>
<ul>

<li>
<b>AI Based Review: </b><small>✔️</small>&nbsp;Successful
</li>

<li>
<b>Static Analysis: </b><small>✔️</small>&nbsp;Successful
</li>

</ul>
</div>
<div>
<h3>High-level Feedback</h3>
Revert changes that incorrectly calculate table row heights to avoid layout issues. Use native JavaScript methods for event handling to prevent performance issues and memory leaks. Replace deprecated event properties with modern standards for future compatibility. Maintain accessibility by using custom outline styles instead of removing them. Manage focus explicitly to ensure consistent and accessible user experience.
</div>
<br>

<div>
<h3>Actionable Issues</h3>

<div id="issue">
<div>
:page_facing_up: opus/application/static_media/js/browse.js
</div>
<details>
<summary>
Issues: Total - 3, High importance - 3
</summary>
<div>


<table width="100%">
<tbody>

<tr>
<td width="30%">
<a href ="https://github.com/SETI/rms-opus/pull/1387/files#r1710506048">Line 585-593</a>
</td>
<td width="70%">
 <small>🔴</small> High importance - 1 &nbsp;&nbsp; 
</td>
</tr>

<tr>
<td width="30%">
<a href ="https://github.com/SETI/rms-opus/pull/1387/files#r1710506059">Line 667-681</a>
</td>
<td width="70%">
 <small>🔴</small> High importance - 1 &nbsp;&nbsp; 
</td>
</tr>

<tr>
<td width="30%">
<a href ="https://github.com/SETI/rms-opus/pull/1387/files#r1710506074">Line 1081-1082</a>
</td>
<td width="70%">
 <small>🔴</small> High importance - 1 &nbsp;&nbsp; 
</td>
</tr>

</tbody>
</table>

</div>
</details>
</div>

<div id="issue">
<div>
:page_facing_up: opus/application/static_media/css/opus.css
</div>
<details>
<summary>
Issues: Total - 1, High importance - 1
</summary>
<div>


<table width="100%">
<tbody>

<tr>
<td width="30%">
<a href ="https://github.com/SETI/rms-opus/pull/1387/files#r1710506100">Line 274-276</a>
</td>
<td width="70%">
 <small>🔴</small> High importance - 1 &nbsp;&nbsp; 
</td>
</tr>

</tbody>
</table>

</div>
</details>
</div>

<div id="issue">
<div>
:page_facing_up: opus/application/static_media/js/opus.js
</div>
<details>
<summary>
Issues: Total - 1, High importance - 1
</summary>
<div>


<table width="100%">
<tbody>

<tr>
<td width="30%">
<a href ="https://github.com/SETI/rms-opus/pull/1387/files#r1710506118">Line 807-807</a>
</td>
<td width="70%">
 <small>🔴</small> High importance - 1 &nbsp;&nbsp; 
</td>
</tr>

</tbody>
</table>

</div>
</details>
</div>

</div>




<span><i>AI Code Review powered by</i> <sub><sub><a href="https://bito.ai/" target="_blank">Bito Logo</a></sub></sub></span>

</div>

File: opus/application/static_media/js/browse.js [hunk 2]
```diff
@@ -575,7 +578,19 @@ var o_browse = {
...
         $(document).on("keydown click", function(e) {
+            // Whenever we click or hit up/down arrows, page up and page down keys, we
+            // want to make sure the ps container is hovered and ps is focused so the the
+            // keydown event will be properly handled by ps.
+            if (opus.prefs.view === "browse" && (e.type === "click" ||
+                (e.which || e.keyCode) == 38 || (e.which || e.keyCode) == 40 ||
+                (e.which || e.keyCode) == 33 || (e.which || e.keyCode) == 34)) {
+                o_browse.hoverAndFocusOnPS();
+            }
+
```
Comment (rfrenchseti) [inline opus/application/static_media/js/browse.js]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/SETI/rms-opus/pull/1387#issuecomment-2276954910>#c06976</a><span> - 08/09/2024, 12:49 am</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> The use of 'e.which' and 'e.keyCode' is deprecated and may not be supported in future versions of browsers. This can lead to potential issues with cross-browser compatibility and future-proofing the code.
</div>
<div id="fix">
<b>Fix:</b> Replace the deprecated 'e.which' and 'e.keyCode' with 'e.key' or 'e.code' to ensure future compatibility and adherence to modern standards.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -588,6 +588,6 @@
              if (opus.prefs.view === "browse" && (e.type === "click" ||
 -                (e.which || e.keyCode) == 38 || (e.which || e.keyCode) == 40 ||
 -                (e.which || e.keyCode) == 33 || (e.which || e.keyCode) == 34)) {
 +                e.key === "ArrowUp" || e.key === "ArrowDown" ||
 +                e.key === "PageUp" || e.key === "PageDown")) {
                  o_browse.hoverAndFocusOnPS();
              }
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: opus/application/static_media/js/browse.js [hunk 3]
```diff
@@ -649,6 +664,21 @@ var o_browse = {
...
+    // same behavior.
+    hoverAndFocusOnPS: function() {
+        let view = opus.prefs.view;
+        let tab = opus.getViewTab(view);
+        let contentsView = o_browse.getScrollContainerClass(view);
+
+        $(`${tab} ${contentsView}`).mouseover();
+        $(`${tab} ${contentsView} .ps__thumb-y`).focus();
+    },
+
```
Comment (rfrenchseti) [inline opus/application/static_media/js/browse.js:703]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/SETI/rms-opus/pull/1387#issuecomment-2276954910>#c06976</a><span> - 08/09/2024, 12:49 am</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> The use of jQuery's '.mouseover()' and '.focus()' methods can lead to unexpected behavior, especially in dynamic content scenarios. This can cause performance issues and potential memory leaks if not handled properly.
</div>
<div id="fix">
<b>Fix:</b> Consider using native JavaScript methods to handle the focus and mouseover events. Additionally, ensure that these events are properly cleaned up to avoid memory leaks.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -678,7 +678,7 @@
         let view = opus.prefs.view;
         let tab = opus.getViewTab(view);
         let contentsView = o_browse.getScrollContainerClass(view);

 -       $('${tab} ${contentsView}').mouseover();
 -       $('${tab} ${contentsView} .ps__thumb-y').focus();
 +       const container = document.querySelector('${tab} ${contentsView}');
 +       const thumb = container.querySelector('.ps__thumb-y');
 +       if (container && thumb) {
 +           container.dispatchEvent(new Event('mouseover'));
 +           thumb.focus();
 +       }
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: opus/application/static_media/js/browse.js [hunk 4]
```diff
@@ -1048,8 +1078,8 @@ var o_browse = {
         // Note: in table view, if there are more than one row, we divide by the 2nd table tr's
         // height because in some corner cases, the first table tr's height will be 1px larger
         // than rest of tr, and this will mess up the calculation.
-        let tableRowHeight = ($(`${tab} tbody tr`).length === 1 ? $(`${tab} tbody tr`).outerHeight() :
-                              $(`${tab} tbody tr`).eq(1).outerHeight());
+        let tableRowHeight = ($(`${tab} tbody tr`).length === 1 ? $(`${tab} tbody tr td`).outerHeight() :
+                              $(`${tab} tbody tr td`).eq(1).outerHeight());
```
Comment (rfrenchseti) [inline opus/application/static_media/js/browse.js:1104]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/SETI/rms-opus/pull/1387#issuecomment-2276954910>#c06976</a><span> - 08/09/2024, 12:49 am</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> The change from 'tbody tr' to 'tbody tr td' in the jQuery selector may lead to incorrect height calculations. The original code calculates the height of the table row, while the updated code calculates the height of the table cell. This could lead to layout issues if the table cells have different heights or if there are multiple cells in a row.
</div>
<div id="fix">
<b>Fix:</b> Revert the change to ensure the height of the table row is calculated correctly. If the intention is to handle single-cell rows differently, additional logic should be added to handle that case specifically.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -1081,2 +1081,2 @@
 - let tableRowHeight = ($('${tab} tbody tr').length === 1 ? $('${tab} tbody tr td').outerHeight() :
 - $('${tab} tbody tr td').eq(1).outerHeight());
 + let tableRowHeight = ($('${tab} tbody tr').length === 1 ? $('${tab} tbody tr').outerHeight() :
 + $('${tab} tbody tr').eq(1).outerHeight());
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: opus/application/static_media/css/opus.css [hunk 5]
```diff
@@ -270,6 +270,11 @@ so that both "Recent Announcements" and "Message" can be vertically aligned. */
     background-color: transparent !important;
 }
 
+/* remove the highlight border of ps when it's focus */
+.op-gallery-contents .ps__thumb-y:focus {
+    outline: none;
+}
```
Comment (rfrenchseti) [inline opus/application/static_media/css/opus.css:276]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/SETI/rms-opus/pull/1387#issuecomment-2276954910>#c06976</a><span> - 08/09/2024, 12:49 am</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> Removing the outline on focus can negatively impact accessibility. Users who rely on keyboard navigation may find it difficult to determine which element is currently focused.
</div>
<div id="fix">
<b>Fix:</b> Instead of removing the outline entirely, consider using a custom outline style that maintains accessibility while achieving the desired visual effect.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -274,3 +274,3 @@
  .op-gallery-contents .ps__thumb-y:focus {
 -    outline: none;
 +    outline: 2px solid #000; /* Example: Use a custom outline style */
  }
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

File: opus/application/static_media/js/opus.js [hunk 6]
```diff
@@ -802,6 +802,9 @@ var opus = {
                 return true;  // they clicked the brand icon, take them to its link
             }
 
+            // Focus out of the nav bar so that up/down and left/right arrow keys won't
+            // jump between different tabs
+            e.target.blur();
```
Comment (rfrenchseti) [inline opus/application/static_media/js/opus.js:807]: <div>

<strong>Bito Code Review Agent Run</strong> <a href=https://github.com/SETI/rms-opus/pull/1387#issuecomment-2276954910>#c06976</a><span> - 08/09/2024, 12:49 am</span>
<br>

<div><small>🔴</small> High importance</div>

<div id="suggestion">
<div id="issue">
<b>Issue:</b> The use of 'e.target.blur()' to remove focus from the nav bar might cause unexpected behavior if the focus is needed elsewhere. This can lead to accessibility issues, especially for keyboard-only users who rely on focus indicators to navigate.
</div>
<div id="fix">
<b>Fix:</b> Instead of blurring the target element, consider managing focus more explicitly. For example, set focus to a specific element that should receive it after the nav bar loses focus. This ensures that the user experience remains consistent and accessible.
</div>
<details>
<summary>
<b>Code suggestion</b>
</summary>
<div id="code">

```
 @@ -804,0 +805,5 @@ var opus = {
 +            // Focus out of the nav bar so that up/down and left/right arrow keys won't
 +            // jump between different tabs
 +            // Instead of blurring, set focus to a specific element
 +            document.getElementById('desired-element-id').focus();
```
</div>
</details>
</div>
<br>


</div>

Is this a valid issue, or was it incorrectly flagged by the Agent?
- [ ] it was incorrectly flagged

**Comment by juzen2003** [comment]
Fixed two issues in the previous comments. Tested on Mac Chrome/FireFox/Safari, Windows Chrome/FireFox/Edge.

**Review by rfrenchseti — CHANGES_REQUESTED** [review]
The problem with the arrow keys being used while on the Browse tab with a Help pane open is only partially fixed. Now when go to the Browse tab, click on a thumbnail to get a slideshow, and then open the Help, the Help pane won't scroll using the keys. But if there's no slideshow open, the Help pane works properly.

**Review by rfrenchseti — CHANGES_REQUESTED** [review]
On the Cart tab (with a lot of items in the cart), if you drag the slider and leave the mouse over the slider, the up/down arrow keys don't do anything. But they work if you move the mouse into the thumbnail browse area.

**Comment by rfrenchseti** [comment]
The ESCAPE key is now broken on the slideshow. If you click on a thumbnail to open the slideshow, then press ESC, the window doesn't close. But if you click somewhere inside the slideshow dialog or even on the background thumbs and then press ESC, it works.

**Review by rfrenchseti — APPROVED** [review]
There are still some issues with the Cart tab that should be addressed separately:

- Drag the slider and release; press up or down arrow once and nothing happens; press a second time and the scrollbar moves
- Drag the slider and while dragging move the mouse far off vertically (like to the lower-right corner of the browser); when you release, the slider will snap back to where it started from. This doesn't happen on the Browse tab.
- Make the browser small so the Download Data pains becomes a pop-out. Pop it out. Now the arrow keys no longer doing anything on that pane (scrolling the list of products), they always move the thumbnails in the background.
