### PR TITLE
Fixed multiple tooltips issues (1265, 1273, 1274)

### LINKED ISSUE #1265: Tooltips show up in bad location after table sort
Go to the Table View. Click on a table header to change the sort order and then while the sort is happening move the mouse to some row in the middle of the browser. 

While we're at it, can we make the tooltip anchor to the top of the current row, not the mouse position? The tooltip often partially obscures the row you're trying to look at.

### LINKED ISSUE #1273: Tooltips in wrong location in gallery view
In the gallery view, there are two indications that can appear at the top of each thumbnail: the tiny binoculars showing this thumbnail was previously shown in the slideshow view, and the word "DETAIL" showing this thumbnail is the observation currently shown on the Detail tab. Both of these indications have tooltips, but they show up in the wrong place. The Binoculars tooltip shows up centered on the thumbnail, and the Detail tooltip shows up on the far left.

### LINKED ISSUE #1274: Tooltip position and timing issues
Various tooltips show up in locations that block easy viewing:

- In table view, the tooltip shows up at the mouse location, instead of at the top of the row, thus blocking the contents of the row you're trying to look at.
- In the slideshow view "edit" mode, the tooltips for the trashcan and the "+ Add field here" show up above the given item, but this blocks much of the area being edited. These are short strings and it would be nicer if they appeared off to the left out of the way.
- In the slideshow view, the tooltip for the "add cart" icon at the bottom shows up off-center. Same for the left arrow button.

### PR DESCRIPTION
**Pull request by juzen2003**
- Fixes #1265 Fixed #1273 Fixed #1274
- Were any Django, import pipeline, or table_schema files modified? N
  - If YES:
    - Database used (or new import): opus3_test_230109
    - FLAKE8 run on modified code: Y
    - All Django tests pass: Y
    - Code coverage run and still at 100%: Y
- Were any JavaScript or CSS files modified? Y
  - If YES:
    - JSHINT run on all affected files: Y
    - Tested on Chrome, Firefox, Safari, Edge, and iOS: Y
      (Remember to test all browser sizes)
    - Tested for race conditions (with delayed API calls if applicable): NA
- Was the documentation reviewed for necessary changes or additions? NA
  - About
  - Getting Started
  - FAQ
  - API Guide
  - Tooltips
  - Import/database schema

Description of changes:
- Update the position of browse table row tooltips, instead of sticking to the cursor, it will now stay at the top border of the table row. (1265, 1274)
- Update the position of the gallery "Detail" icon tooltip, it will now stay at the top of the "Detail" icon. (1273)
- Update the position of the gallery binoculars icon tooltip, it's now at the top of the binoculars icon. (1273)
- Update the position of "+" and trash icons tooltips in the edit menu of metadata detail box, now they will show up at the left of the icons (won't block the menu). (1274)
- Fixed the positions of the tooltips for cart, hamburger, prev, and next icons in metadata box, now tooltips will show up at the centered top of the icons. (1274)
- Increase the delay of tooltips on the gallery and table view, change from 0.5s to 1s. (1274)

Known problems:
- Was not able to reproduce the issue that tooltips of the table view show up at bad location when sorting is happening (1265)

### CODE REVIEW

File: opus/application/static_media/js/browse.js [hunk 1]
```diff
@@ -1819,7 +1820,7 @@ var o_browse = {
                 galleryHtml += '<div class="op-modal-overlay">';
                 galleryHtml += '<p class="content-text"><i class="fas fa-binoculars fa-4x text-info" aria-hidden="true"></i></p>';
                 galleryHtml += '</div></a>';
-                galleryHtml += `<div class="op-last-modal-overlay text-success op-hide-element op-browse-gallery-tooltip" title="Last viewed in slideshow mode"></div>`;
+                galleryHtml += `<div class="op-last-modal-overlay text-success op-hide-element op-browse-gallery-bino-tooltip" title="Last viewed in slideshow mode"></div>`;
```
Comment (dstopp) [inline opus/application/static_media/js/browse.js]: minor comment - I had to hunt to figure out what "bino" referred to; might want to consider changing it to "binocular" or "binoculars"

File: opus/application/static_media/js/browse.js [hunk 2]
```diff
@@ -8,6 +8,7 @@
 /* globals MAX_SELECTIONS_ALLOWED */
 
 const infiniteScrollUpThreshold = 100;
+const galleryAndTableTooltipsDelay = 1000;
```
Comment (dstopp) [inline opus/application/static_media/js/browse.js:11]: curious why this delay needs to be different from the original tooltip delay

Comment (rfrenchseti) [reply opus/application/static_media/js/browse.js:11]: Because that was the bug: "Also I think the tooltips on the gallery and table view show up way too fast, and often get in the way of trying to see things nearby. Can we add a little more delay?"

**Review by rfrenchseti — APPROVED** [review]
